# ! 以下配置项均为必检查项 !
# 真实比赛模式 比赛必须设置为 true , 设置为 false 则会调用内录
RealCompetitionMode: true

Communication:
  # broker 的 IP 地址
  address: 'tcp://localhost:1883'

PointCloud:
  # 用于初始化的采样点量 单位: 批次
  sampleSize: 100
  # ! 以下为回放选项, 仅在 RealCompetitionMode 为 false 时需要配置 !
  replay:
    # 回放路径 (建议别填, 便于在场上发现错误)
    path: ''

TransForm:
  localTrans:
    # 是否启用本地参数
    # true: 采用下面的参数
    # false: 采用服务器发送的参数
    # ! 比赛应该设置为 false !
    enable: false
    # 本地参数 旋转矩阵
    rotMat:  [[-0.15388790523817936, -0.9880761955592113, -0.0048203854286677774],
              [-0.37946886466912755, 0.06360347452090469, -0.9230152441877383],
              [0.9123167437282229, -0.1402114673925578, -0.3847322302923907]]
    # 本地参数 平移向量 单位: mm
    transVec: [9309.91421417037, 2661.1087605698353, 3684.8470948593963]
  autoAlign:
    # 是否使用基于前面标定结果的辅助自动对齐 场上推荐启用
    enable: true
  manualAlign:
    # 是否手动标定 启用时**不会**使用本地和服务器发送的EPNP数据 必要时启用
    enable: false
